### ISSUE TITLE
下载好像过期了，可以再上传一下吗😭

### ISSUE THREAD

**Issue by SisCleaire** [ryoii/mirai-rate-limit#2]

**Comment by ryoii** [comment]
fork 一下随便提交点什么应该就会触发构建了，workflow 脚本应该是好的

**Comment by SisCleaire** [comment]
fork了，但不是很会弄这个，可以麻烦您重新构建下不😭

**Comment by ryoii** [comment]
好了

**Comment by SisCleaire** [comment]
感谢佬！！！

**Comment by ryoii** [comment]
不客气

**Comment by SisCleaire** [comment]
抱歉再打扰一下您，如果我想设置成全局至多2秒发送一条消息的话，这样是不是就可以啦：
```
global: 
  enable: true
  behavior: wait
  warmUp: 0
  burstFactor: 0.0
  limit: 1
  duration: 2s
```
